# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print help message
    cmds:
      - task --list
    silent: true

  linter:
    desc: Run mypy
    cmds:
      - mypy src/ schemas/ scripts/ function_app.py

  tests-unit:
    desc: Run unit tests
    cmds:
      - mypy tests/
      - pytest tests/ --ignore tests/integration
    env:
      PYTHONPATH: "{{.ROOT_DIR}}"
    interactive: true
  
  tests-int:
    desc: Run integration tests
    cmds:
      - mypy tests/
      - pytest tests/integration
    env:
      PYTHONPATH: "{{.ROOT_DIR}}"
      RUNTIME_ENV: "DEV"
    interactive: true

  tests-all:
    desc: Run all tests
    deps: [tests-unit, tests-int]
    failfast: true
    interactive: true

  tests-stage:
    desc: Run all tests emulating github actions staging env.
    cmds:
      - act -W '.github/workflows/test.yml' --rm
    interactive: true

  run-dev:
    desc: Run function app in dev mode
    cmds:
      - func start

  run-prod:
    desc: Run function app in production mode
    cmds:
      - func start
    env:
      TARGET_ENV: PROD

  list-jobs:
    desc: List current jobs in Azure runtime
    cmds:
      - python -m scripts.health_checks tasks {{.CLI_ARGS}}

  list-missing:
    desc: List missing files in pipeline
    cmds:
      - python -m scripts.health_checks files {{.CLI_ARGS}}

  kill-jobs:
    desc: Kill running jobs in Azure runtime
    cmds:
      - python -m scripts.health_checks kill {{.CLI_ARGS}}

  label-data:
    desc: Create small dataset to manually label in Argilla/HF web interface
    cmds:
      - python scripts/labeling.py --action add

  download-labels:
    desc: Download labeled dataset from Argilla HF space
    cmds:
      - python scripts/labeling.py --action download

