from typing import Protocol
from azure.storage.blob import BlobServiceClient

DEFAULT_CONNECTION: str = "AzureWebJobsStorage"

class BlobStorageProtocol(Protocol):
    def __init__(self, container, key = DEFAULT_CONNECTION):
        self.container = container
        self.key = key

    def get_connection_key(self): ...

    def get_blob_service_client(self) -> BlobServiceClient: ...

    def exists_container(self) -> bool: ...

    def create_container(self) -> None: ...

    def exists_blob(self, blob_name) -> bool: ...

    def list_blobs(self) -> list[str]: ...

    def load_metadata(self, name) -> dict: ...

    def load_blob(self, name) -> bytes: ...

    def upload_blob(self, data, blob_name, content_type, metadata=None) -> None: ...

    def upload_metadata(self, data, blob_name) -> None: ...

    def remove_blob(self, blob_name) -> None: ...

